# Generated by Django 5.1.4 on 2025-01-16 04:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_product_imageurl'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='imageUrl',
        ),
    ]
